language: cpp
compiler:
- g++
- clang++
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq cmake openssl libssl-dev libboost-all-dev clang-3.4
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CC="gcc-4.8" CXX="g++-4.8"; fi
script:
- mkdir build
- cd build
- cmake ..
- make -j3
notifications:
  slack:
    secure: OGTNEAIvRI+OCW55HwA2aF1EQczBhAhBPiZ4qs3xNruRb5gZDMlFU4RU93ECexMYlr17rrxPOSFQUceLAcTrvj5sv7EjcRdANgthM5bTUzBCL9NQLiYw5MVWvJ1AcSk+0EyUkH2u/pQiq1Hg7FJ7EK0EFkip//7J5dhyN6o9378=
