language: c
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq > /dev/null
- sudo apt-get install -qq cmake openssl libssl-dev > /dev/null
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
script:
- mkdir build
- cd build
- cmake ..
- make -j3
notifications:
  slack:
    secure: OGTNEAIvRI+OCW55HwA2aF1EQczBhAhBPiZ4qs3xNruRb5gZDMlFU4RU93ECexMYlr17rrxPOSFQUceLAcTrvj5sv7EjcRdANgthM5bTUzBCL9NQLiYw5MVWvJ1AcSk+0EyUkH2u/pQiq1Hg7FJ7EK0EFkip//7J5dhyN6o9378=
