language: c
compiler:
- gcc
- clang
before_install:
- sudo apt-get update -qq > /dev/null
- sudo apt-get install -qq cmake openssl libssl-dev > /dev/null
script:
- mkdir build
- cd build
- cmake ..
- make -j3
